spring.application.name=usermgr

spring.datasource.url=jdbc:mysql://localhost:3306/usermanager?serverTimezone=UTC&useSSL=false&autoReconnect=true
spring.datasource.username=devuser
spring.datasource.password=devuser
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# JPA / Hibernate
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=true

# HikariCP connection pool
spring.datasource.hikari.maximum-pool-size=10
spring.datasource.hikari.minimum-idle=5
spring.datasource.hikari.idle-timeout=600000
spring.datasource.hikari.connection-timeout=30000
spring.datasource.hikari.max-lifetime=1800000

# Security
logging.level.org.springframework.security=TRACE
spring.security.oauth2.resourceserver.jwt.issuer-uri=https://idpgw.test4mind.com/realms/demo-interview
spring.security.oauth2.resourceserver.jwt.jwt-set-uri=${spring.security.oauth2.resourceserver.jwt.issuer-uri}/protocol/openid-connect/certs